package cl.kanopus.launcher.view;

import cl.kanopus.MyApplication;
import cl.kanopus.local.service.PrinterService;
import cl.kanopus.local.web.PrinterController;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.List;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.pdfbox.io.IOUtils;
import org.springframework.boot.ExitCodeGenerator;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author godheaven
 */
public class Home extends javax.swing.JFrame {

    int xMouse, yMouse;
    private ConfigurableApplicationContext ctx;
    private PrinterService printerService;
    private final String PREFERENCES = System.getProperty("java.io.tmpdir") + File.separator + "kanopus-services.properties";

    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();

        setLocationRelativeTo(null);
        setVisible(false);
        if (ctx == null) {
            ctx = SpringApplication.run(MyApplication.class);
            printerService = ctx.getBean(PrinterService.class);
        }

        try {
            //Cargamos el archivo de preferencias
            File file = new File(PREFERENCES);
            if (file.exists()) {
                Properties property = new Properties();
                property.load(new FileReader(file));

                PrinterController.printer = property.getProperty("printer");
                PrinterController.paper = property.getProperty("paper");
            }
        } catch (Exception ex) {
            System.err.println("No es posible leer el archivo de preferencias: " + ex.getMessage());
        }

        loadPrinters();
        jRadioButton1ItemStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jImpresoras = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        JLabelPapel = new javax.swing.JLabel();
        jLabelImpresora = new javax.swing.JLabel();
        boton_cerrar = new javax.swing.JLabel();
        boton_imprimir = new javax.swing.JLabel();
        jButtonHide = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setTitle("Kanopus");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jImpresoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jImpresoras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jImpresorasItemStateChanged(evt);
            }
        });
        getContentPane().add(jImpresoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("80 mm");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 108, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("58 mm");
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 108, -1));

        JLabelPapel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JLabelPapel.setForeground(new java.awt.Color(255, 255, 255));
        JLabelPapel.setLabelFor(jRadioButton1);
        JLabelPapel.setText("Papel");
        getContentPane().add(JLabelPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabelImpresora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelImpresora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImpresora.setLabelFor(jImpresoras);
        jLabelImpresora.setText("Impresora");
        getContentPane().add(jLabelImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        boton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_exit1.png"))); // NOI18N
        boton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_cerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_cerrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_cerrarMouseEntered(evt);
            }
        });
        getContentPane().add(boton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 210, 40));

        boton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_print1.png"))); // NOI18N
        boton_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_imprimirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_imprimirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_imprimirMouseEntered(evt);
            }
        });
        getContentPane().add(boton_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 210, 40));

        jButtonHide.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonHide.setText("X");
        jButtonHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHideMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, -1));

        barra_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        barra_superior.setOpaque(false);

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(barra_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHideMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonHideMouseClicked

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void boton_imprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_imprimirMouseEntered
        boton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_print2.png"))); // NOI18N
    }//GEN-LAST:event_boton_imprimirMouseEntered

    private void boton_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cerrarMouseEntered
        boton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_exit2.png"))); // NOI18N
    }//GEN-LAST:event_boton_cerrarMouseEntered

    private void boton_imprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_imprimirMouseExited
        boton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_print1.png"))); // NOI18N
    }//GEN-LAST:event_boton_imprimirMouseExited

    private void boton_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cerrarMouseExited
        boton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_exit1.png"))); // NOI18N
    }//GEN-LAST:event_boton_cerrarMouseExited

    private void boton_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cerrarMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar la aplicación?", "Alerta", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                //Guardamos en el archivo de preferencias
                Properties property = new Properties();
                property.setProperty("printer", PrinterController.printer);
                property.setProperty("paper", PrinterController.paper);
                property.store(new FileWriter(PREFERENCES), "Preferencias de impresora");
            } catch (Exception ex) {
                System.err.println("No es posible guardar en el archivo de preferencias: " + ex.getMessage());
            }

            //Cerramos la la aplicacion local
            int exitCode = SpringApplication.exit(ctx, (ExitCodeGenerator) () -> 0);
            System.exit(exitCode);

        }
    }//GEN-LAST:event_boton_cerrarMouseClicked

    private void boton_imprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_imprimirMouseClicked
        try {
            byte[] pdf = IOUtils.toByteArray(getClass().getResource("/pdf/test_" + PrinterController.paper + ".pdf").openStream());
            printerService.printThermal(pdf, PrinterController.printer);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_imprimirMouseClicked

    private void jImpresorasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jImpresorasItemStateChanged
        PrinterController.printer = (String) jImpresoras.getSelectedItem();
    }//GEN-LAST:event_jImpresorasItemStateChanged

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        PrinterController.paper = jRadioButton1.isSelected() ? PrinterController.PAPER_80mm : PrinterController.PAPER_58mm;
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    public void toggle() {
        setVisible(!isVisible());
        if (isVisible()) {
            loadPrinters();
        }
    }

    private void loadPrinters() {
        try {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            List<String> impresoras = printerService.getPrinters();
            for (String impresora : impresoras) {
                model.addElement(impresora);
            }

            if (PrinterController.printer != null) {
                model.setSelectedItem(PrinterController.printer);
                jImpresoras.setModel(model);
            } else if (!impresoras.isEmpty()) {
                PrinterController.printer = impresoras.get(0);
                jImpresoras.setModel(model);
                jImpresoras.setSelectedIndex(0);
            } else {
                jImpresoras.setModel(model);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención!", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelPapel;
    private javax.swing.JLabel background;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JLabel boton_cerrar;
    private javax.swing.JLabel boton_imprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jButtonHide;
    private javax.swing.JComboBox<String> jImpresoras;
    private javax.swing.JLabel jLabelImpresora;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
